CREATE TABLE IF NOT EXISTS blogtable (
id INTEGER GENERATED ALWAYS AS IDENTITY
(START WITH 1 
INCREMENT BY 1 
NO CYCLE),
blog STRING,
PRIMARY KEY (id))

CREATE TABLE IF NOT EXISTS blogtable (
id integer,
blog STRING,
PRIMARY KEY (id))

